### ISSUE TITLE
EasyEDA schematics & HDR connections

### ISSUE THREAD

**Issue by ivosak** [zircothc/DRUM_2004_V1#2]
Hello,

Please can you share also EasyEDA project link so we could copy PCB and order it :-)

Than I would like to ask for what are connectors **J2, J4 & I2C** for? What should be connected to them?

Thank you a lot!

**Comment by zircothc** [comment]
Hi. 

https://oshwlab.com/zircothc/esp32-drum-synth-lofi-machine
https://easyeda.com/editor#project_id=08f629c08b18444ca16accbb2242c0fb

I forgot to print labels for that pins. It is my second ordered PCB, excuse me ;)
These are free pins, not used, so you can attach more buttons, or add MIDI serial. 
Communication isthe main porpouse.
The square marked pin at PCB is GND. Next is 3.3v, and the free pins.
Also I2c pins to use I2c devices :)
I have a pair of I2c modules I build with lots of rotaries but not so much time to play with it :(
I'm using J4 for serial to get a poor but simple sync system I'm testing now. 

![IMG_20240523_184414](https://github.com/zircothc/DRUM_2004_V1/assets/17828930/a9c61876-e5cd-4efa-a4a7-4f7583a63e2e)
![IMG_20240523_184402](https://github.com/zircothc/DRUM_2004_V1/assets/17828930/f371dd6c-2a14-42f5-9d47-ccb2acd71294)

**Comment by ivosak** [comment]
Thank you a lot!
