### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ivosak** [zircothc/DRUM_2004_V1#3]
Hello,
I just downloaded your project and not able to compile.
Any Idea?

[Compile-error.txt](https://github.com/zircothc/DRUM_2004_V1/files/15445115/Compile-error.txt)

Thank you
Ivo

**Comment by zircothc** [comment]
Hi.
Your esp32 board version is 2.0.16.
Mine is 2.0.14.
I will test It.
Thanks.

**Comment by porkcube** [comment]
I got the same with Arduino IDE `2.3.2`, using `1.8.19` as called out in the README worked fine.

**Comment by ivosak** [comment]
mea culpa, mea maxima culpa
after reinstalling Aruduino and board, it works fine.

I needed to install also library **_Keypad.h_**, I guess it is this one: [https://github.com/Chris--A/Keypad](https://github.com/Chris--A/Keypad)
Correct?

**Comment by porkcube** [comment]
Yeah that's that one I have installed in both 1.8.19 and should work.

**Comment by ivosak** [comment]
great, thanks.
Waiting for Lolin S2 Mini (ESP32 S2) arrival and PCB and try it. Looking forward for new toy :)
Thank you for help!
Ivo
