### ISSUE TITLE
error to compile

### ISSUE THREAD

**Issue by SKALOVSK** [zircothc/DRUM_2004_V1#6]
I'm trying to compile the project but this error appears and I can't resolve it.

Arduino: 1.8.19 (Windows 10), Placa:"LOLIN S2 Mini, Enabled, Disabled, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), None, Disabled"

In file included from C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\DRUM_2024_V1.ino:27:

tablesESP32_E.h:1090:1: error: narrowing conversion of '128' from 'int' to 'signed char' inside { } [-Wnarrowing]

 };

 ^

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino: In function 'void synthESP32_begin()':

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:4:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpfL.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:5:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpfR.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:10:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf0.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:11:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf1.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:12:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf2.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:13:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf3.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:14:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf4.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:15:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf5.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:16:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf6.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:17:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf7.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:18:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf8.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:19:21: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf9.setResonance(reso);

                     ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:20:22: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf10.setResonance(reso);

                      ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:21:22: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf11.setResonance(reso);

                      ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:22:22: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf12.setResonance(reso);

                      ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:23:22: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf13.setResonance(reso);

                      ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:24:22: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf14.setResonance(reso);

                      ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:25:22: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '511' to '255' [-Woverflow]

   lpf15.setResonance(reso);

                      ^~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:48:49: warning: 'I2S_COMM_FORMAT_I2S' is deprecated [-Wdeprecated-declarations]

     .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),

                                                 ^~~~~~~~~~~~~~~~~~~

In file included from C:\Users\vitor.moraes.NAGSORRI0\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17/tools/sdk/esp32s2/include/driver/include/driver/i2s.h:16,

                 from C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\DRUM_2024_V1.ino:25:

C:\Users\vitor.moraes.NAGSORRI0\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17/tools/sdk/esp32s2/include/hal/include/hal/i2s_types.h:87:5: note: declared here

     I2S_COMM_FORMAT_I2S       __attribute__((deprecated)) = 0x01, /*!< I2S communication format I2S, correspond to `I2S_COMM_FORMAT_STAND_I2S`*/

     ^~~~~~~~~~~~~~~~~~~

C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\synthESP32.ino:48:71: warning: 'I2S_COMM_FORMAT_I2S_MSB' is deprecated [-Wdeprecated-declarations]

     .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),

                                                                       ^~~~~~~~~~~~~~~~~~~~~~~

In file included from C:\Users\vitor.moraes.NAGSORRI0\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17/tools/sdk/esp32s2/include/driver/include/driver/i2s.h:16,

                 from C:\Users\vitor.moraes.NAGSORRI0\Desktop\Drum\DRUM_2004_V1-main\DRUM_2024_V1\DRUM_2024_V1.ino:25:

C:\Users\vitor.moraes.NAGSORRI0\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17/tools/sdk/esp32s2/include/hal/include/hal/i2s_types.h:88:5: note: declared here

     I2S_COMM_FORMAT_I2S_MSB   __attribute__((deprecated)) = 0x01, /*!< I2S format MSB, (I2S_COMM_FORMAT_I2S |I2S_COMM_FORMAT_I2S_MSB) correspond to `I2S_COMM_FORMAT_STAND_I2S`*/

     ^~~~~~~~~~~~~~~~~~~~~~~

exit status 1

narrowing conversion of '128' from 'int' to 'signed char' inside { } [-Wnarrowing]

**Comment by zircothc** [comment]
Hi.
There is an error in the the github project name , "2004" instead of "2024". Sorry.
So I`ve downloaded github project, **rename** zip file "DRUM_2004_V1-main.zip" to "DRUM_2024_V1..zip", and extracted.
Select "Lolin S2 Mini" with defaults.
My Arduino IDE versión now is **2.3.2** and ESP32 boards version for thisd project is 
**2.0.17**
Newer versions can't compile; some issues with "uclock" library.
Try to clean your temp folder.
If this is not a solution may you need to unistall and reinstall IDE and libraries again
Hope it helps.
:)

**Comment by SKALOVSK** [comment]
That was exactly it, I downloaded the version indicated there 1.8.19 and plate 2.0.17 and it was, something that was changed in this newer version that does not compile.
