### ISSUE TITLE
Error compiling uClock library not correct ?

### ISSUE THREAD

**Issue by SurvivalHacking** [zircothc/DRUM_2004_V1#8]
Hi, when I try to compile I got some error not in code but in library usage.
There are some updated or different uClock library to be used ?

FQBN: esp32:esp32:lolin_s2_mini
Utilizzo della scheda 'lolin_s2_mini' dalla piattaforma nella cartella: /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5
Utilizzo del core 'esp32' dalla piattaforma nella cartella: /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5

   50 |     _uclockTimer = timerBegin(TIMER_ID, 80, true);
      |                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/cores/esp32/esp32-hal.h:84,
                 from /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/cores/esp32/Arduino.h:36,
                 from /Users/thor/Documents/Arduino/libraries/uClock/src/uClock.h:32,
                 from /Users/thor/Documents/Arduino/libraries/uClock/src/uClock.cpp:28:
/Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/cores/esp32/esp32-hal-timer.h:35:13: note: declared here
   35 | hw_timer_t *timerBegin(uint32_t frequency);
      |             ^~~~~~~~~~
/Users/thor/Documents/Arduino/libraries/uClock/src/platforms/esp32.h:53:25: error: too many arguments to function 'void timerAttachInterrupt(hw_timer_t*, void (*)())'
   53 |     timerAttachInterrupt(_uclockTimer, &handlerISR, false);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/cores/esp32/esp32-hal-timer.h:50:6: note: declared here
   50 | void timerAttachInterrupt(hw_timer_t *timer, void (*userFunc)(void));
      |      ^~~~~~~~~~~~~~~~~~~~
/Users/thor/Documents/Arduino/libraries/uClock/src/platforms/esp32.h:56:5: error: 'timerAlarmWrite' was not declared in this scope; did you mean 'timerWrite'?
   56 |     timerAlarmWrite(_uclockTimer, init_clock, true);
      |     ^~~~~~~~~~~~~~~
      |     timerWrite
/Users/thor/Documents/Arduino/libraries/uClock/src/platforms/esp32.h:59:5: error: 'timerAlarmEnable' was not declared in this scope; did you mean 'timerAlarm'?
   59 |     timerAlarmEnable(_uclockTimer);
      |     ^~~~~~~~~~~~~~~~
      |     timerAlarm
/Users/thor/Documents/Arduino/libraries/uClock/src/platforms/esp32.h: In function 'void setTimer(uint32_t)':
/Users/thor/Documents/Arduino/libraries/uClock/src/platforms/esp32.h:64:5: error: 'timerAlarmWrite' was not declared in this scope; did you mean 'timerWrite'?
   64 |     timerAlarmWrite(_uclockTimer, us_interval, true);
      |     ^~~~~~~~~~~~~~~
      |     timerWrite

Uso la libreria FS alla versione 3.0.5 nella cartella: /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/FS 
Uso la libreria SPIFFS alla versione 3.0.5 nella cartella: /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/SPIFFS 
Uso la libreria U8g2 alla versione 2.35.30 nella cartella: /Users/thor/Documents/Arduino/libraries/U8g2 
Uso la libreria Wire alla versione 3.0.5 nella cartella: /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/Wire 
Uso la libreria Adafruit NeoPixel alla versione 1.12.3 nella cartella: /Users/thor/Documents/Arduino/libraries/Adafruit_NeoPixel 
Uso la libreria uClock alla versione 2.1.0 nella cartella: /Users/thor/Documents/Arduino/libraries/uClock 
Uso la libreria Keypad alla versione 3.1.1 nella cartella: /Users/thor/Documents/Arduino/libraries/Keypad 
Uso la libreria SPI alla versione 3.0.5 nella cartella: /Users/thor/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/SPI 
exit status 1

Compilation error: exit status 1

**Comment by SurvivalHacking** [comment]
Ok, I',m a donkey.
It is because I updated at the latest ESP32 subsystem 3.0.5 and it is not compatible.
I installed 2.0.18 and compile without problems

**Comment by zircothc** [comment]
Uclock library needs to be updated
